### ISSUE TITLE
Builds are failing

### ISSUE THREAD

**Issue by nstuyvesant** [svelte-society/sveltesociety.dev#358]
I just submitted a change to templates.json. The build failed but not due to anything I changed....

```
8:29:01 AM: Unable to find the localStorage. No data will be persisted.
8:29:02 AM: file:///opt/build/repo/node_modules/@sveltejs/kit/src/core/prerender/prerender.js:35
8:29:02 AM: 				throw new Error(format(details));
8:29:02 AM: 				      ^
8:29:02 AM: Error: The following pages contain links to /components#component-Event Calendar, but no element with id="component-Event Calendar" exists on /components - see the `handleMissingId` option in https://kit.svelte.dev/docs/configuration#prerender for more info:
8:29:02 AM:   - /components
8:29:02 AM:     at file:///opt/build/repo/node_modules/@sveltejs/kit/src/core/prerender/prerender.js:35:11
8:29:02 AM:     at prerender (file:///opt/build/repo/node_modules/@sveltejs/kit/src/core/prerender/prerender.js:435:4)
8:29:02 AM: [vite-plugin-sveltekit-build] Prerendering failed with code 1
8:29:02 AM: error during build:
8:29:02 AM: Error: Prerendering failed with code 1
8:29:02 AM:     at ChildProcess.<anonymous> (file:///opt/build/repo/node_modules/@sveltejs/kit/src/exports/vite/index.js:483:15)
8:29:02 AM:     at ChildProcess.emit (node:events:513:28)
8:29:02 AM:     at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
8:29:02 AM: ​
8:29:02 AM:   "build.command" failed                                        
8:29:02 AM: ────────────────────────────────────────────────────────────────
8:29:02 AM: ​
8:29:02 AM:   Error message
8:29:02 AM:   Command failed with exit code 1: npm run build (https://ntl.fyi/exit-code-1)
8:29:02 AM: ​
8:29:02 AM:   Error location
8:29:02 AM:   In Build command from Netlify app:
8:29:02 AM:   npm run build
8:29:02 AM: ​
8:29:02 AM:   Resolved config
8:29:02 AM:   build:
8:29:02 AM:     base: /opt/build/repo
8:29:02 AM:     command: npm run build
8:29:02 AM:     commandOrigin: ui
8:29:02 AM:     environment:
8:29:02 AM:       - NODE_VERSION
8:29:02 AM:       - REVIEW_ID
8:29:02 AM:     publish: /opt/build/repo/build
8:29:02 AM:     publishOrigin: ui
8:29:02 AM: Caching artifacts
8:29:02 AM: Started saving node modules
8:29:02 AM: Finished saving node modules
8:29:02 AM: Started saving build plugins
8:29:02 AM: Finished saving build plugins
8:29:02 AM: Started saving pip cache
8:29:03 AM: Finished saving pip cache
8:29:03 AM: Started saving emacs cask dependencies
8:29:03 AM: Finished saving emacs cask dependencies
8:29:03 AM: Started saving maven dependencies
8:29:03 AM: Finished saving maven dependencies
8:29:03 AM: Started saving boot dependencies
8:29:03 AM: Finished saving boot dependencies
8:29:03 AM: Started saving rust rustup cache
8:29:03 AM: Finished saving rust rustup cache
8:29:03 AM: Started saving go dependencies
8:29:03 AM: Finished saving go dependencies
8:29:03 AM: Build failed due to a user error: Build script returned non-zero exit code: 2
8:29:03 AM: Failing build: Failed to build site
8:29:03 AM: Finished processing build request in 37.492655441s
```

Also, there are lots of warnings from vite-plugin-svelte about missing attributes on links, etc.

**Comment by nstuyvesant** [comment]
https://app.netlify.com/sites/sveltesociety-preview/deploys/63beb9718884bf0008d3a776

**Comment by benmccann** [comment]
I just fixed this
